### ISSUE TITLE
Delegated properties can sometimes cause an NPE

### ISSUE THREAD

**Issue by sykesd** [sykesd/japper#31]
If you have a type like this:

```java
public class Base {
  private String id;
  private String someOtherProperty;
 ...
}
```

and you have a 2nd type that delegates to `Base`, but does not include all properties, e.g.

```java
public class DelegatedBase {
  private String nativeId;
  private Base base = new Base();

  public String getId() { return base.getId(); }

  public void setId(String id) { base.setId(id); }

 // NOTE: No get-/setSomeOtherProperty
}
```

*and* `DelegatedBase` also allows read-only access to the delegate, e.g.
```java
public class DelegatedBase {
  //...
  public Base getBase() { return base; }

  // Note: No setBase()
}
```

Then this causes the mapper generator to throw an NPE:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.dt.japper.MapperCodeGenerator.buildReference(MapperCodeGenerator.java:342)
	at org.dt.japper.MapperCodeGenerator.buildPropertySetter(MapperCodeGenerator.java:209)
	at org.dt.japper.MapperCodeGenerator.buildMapMethodBody(MapperCodeGenerator.java:165)
	at org.dt.japper.MapperCodeGenerator.create(MapperCodeGenerator.java:72)
	at org.dt.japper.GeneratedMapper.get(GeneratedMapper.java:68)
	at org.dt.japper.Japper.getMapper(Japper.java:992)
	at org.dt.japper.Japper.query(Japper.java:281)
	at org.dt.japper.Japper.query(Japper.java:342)
```

**Comment by sykesd** [comment]
#32 includes the fix for this.

**Comment by sykesd** [comment]
Version 0.9.3 includes this fix
